### ISSUE TITLE
Validating Lambda function gives me error

### ISSUE THREAD

**Issue by tango2310** [awslabs/aws-serverless-workshops#31]
I get error message
 
{
  "statusCode": 500,
  "body": "{\"Error\":\"One or more parameter values were invalid: Missing the key RideID in the item\",\"Reference\":\"a05123a5-522c-11e7-86dd-9bc16202cf58\"}",
  "headers": {
    "Access-Control-Allow-Origin": "*"
  }
}
 
Lambda log output says
 
START RequestId: a05123a5-522c-11e7-86dd-9bc16202cf58 Version: $LATEST
2017-06-16T00:42:08.041Z       a05123a5-522c-11e7-86dd-9bc16202cf58  Received event ( ci75T980Y1zFRSlRPW3PXA ):  { path: '/ride',
  httpMethod: 'POST',
  headers: 
   { Accept: '*/*',
     Authorization: 'eyJraWQiOiJLTzRVMWZs',
     'content-type': 'application/json; charset=UTF-8' },
  queryStringParameters: null,
  pathParameters: null,
  requestContext: { authorizer: { claims: [Object] } },
  body: '{"PickupLocation":{"Latitude":47.6174755835663,"Longitude":-122.28837066650185}}' }
2017-06-16T00:42:08.041Z       a05123a5-522c-11e7-86dd-9bc16202cf58  Finding unicorn for  47.6174755835663 ,  -122.28837066650185
2017-06-16T00:42:08.242Z       a05123a5-522c-11e7-86dd-9bc16202cf58  { ValidationException: One or more parameter values were invalid: Missing the key RideID in the item
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'One or more parameter values were invalid: Missing the key RideID in the item',
  code: 'ValidationException',
  time: 2017-06-16T00:42:08.242Z,
  requestId: '3H734FLH2T7OT5KNPUQ8PJEITRVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 32.63472032648866 }
END RequestId: a05123a5-522c-11e7-86dd-9bc16202cf58
REPORT RequestId: a05123a5-522c-11e7-86dd-9bc16202cf58       Duration: 252.40 ms        Billed Duration: 300 ms        Memory Size: 128 MB    Max Memory Used: 34 MB

**Comment by tango2310** [comment]
This issue was in fact my fault.

I had RideID instead of RideId as the primary key name in the DynamoDB table.

Sorry to have bothered anyone.

Todd

**Comment by AkberIqbal** [comment]
or update function by changing the RideId to RideID the [code here](https://github.com/awslabs/aws-serverless-workshops/blob/master/WebApplication/3_ServerlessBackend/requestUnicorn.js)

`function recordRide(rideId, username, unicorn) {
    return ddb.put({
        TableName: 'Rides',
        Item: {
            **RideID**: rideId,
            User: username,
            Unicorn: unicorn,
            UnicornName: unicorn.Name,
            RequestTime: new Date().toISOString(),
        },
    }).promise();
}`

**Comment by baodad** [comment]
@tango2310 Thanks for sharing.  I had the exact same issue, and you helped me recognize it.

**Comment by kingfi** [comment]
@tango2310 thank so much for putting this out there regardless. I too had the same issue, and it was resolved because of this.

**Comment by PrisonerPrice** [comment]
@tango2310 Thank you, bro. I actually had almost the exact problem. Your sharing really helps a lot.

**Comment by AlfianFannani** [comment]
@tango2310 i had same problem, and its helpfully. Thank you!

**Comment by PooGC** [comment]
Thank you, I helped me :)

**Comment by chuka2003** [comment]
thanks for sharing... i won't ever have realized my stupid mistake if not for you

**Comment by philipbutler** [comment]
Lmao so many of us did this exactly

**Comment by ThiagoFelippi** [comment]
I had the same problem, but my error was little stupid :cry: 
I was add the key in serverless.yml with hash type, but when I put the obj I did that:
``` 
 Item: JSON.stringify({
        userId: uuid(),
        username: this.#_username,
        email: this.#_email,
        submittedAt: timestamp,
        updatedAt: timestamp,
}),
```

But the correct is just:
```
    Item: {
        userId: uuid(),
        username: this.#_username,
        email: this.#_email,
        submittedAt: timestamp,
        updatedAt: timestamp,
      },
```

Without JSON.Stringfy({})
